create extension postgis;

-- create table precincts (
-- pct16 varchar,
-- area double precision,
-- geog geography,
-- PRIMARY KEY( pct16 )
-- );

create table results (
pct16 varchar,
pres_clinton double precision,
pres_trump double precision,
pres_johnson double precision,
pres_stein double precision,
pres_lariva double precision,
pres_other double precision,
ussenate_harris double precision,
ussenate_sanchez double precision,
prop51_yes double precision,
prop51_no double precision,
prop52_yes double precision,
prop52_no double precision,
prop53_yes double precision,
prop53_no double precision,
prop54_yes double precision,
prop54_no double precision,
prop55_yes double precision,
prop55_no double precision,
prop56_yes double precision,
prop56_no double precision,
prop57_yes double precision,
prop57_no double precision,
prop58_yes double precision,
prop58_no double precision,
prop59_yes double precision,
prop59_no double precision,
prop60_yes double precision,
prop60_no double precision,
prop61_yes double precision,
prop61_no double precision,
prop62_yes double precision,
prop62_no double precision,
prop63_yes double precision,
prop63_no double precision,
prop64_yes double precision,
prop64_no double precision,
prop65_yes double precision,
prop65_no double precision,
prop66_yes double precision,
prop66_no double precision,
prop67_yes double precision,
prop67_no double precision,
pres_clinton_per double precision,
pres_trump_per double precision,
pres_third_per double precision,
pres_winner varchar,
pres_margin double precision,
votedensity double precision,
prop51_yes_per double precision,
prop51_no_per double precision,
prop52_yes_per double precision,
prop52_no_per double precision,
prop53_yes_per double precision,
prop53_no_per double precision,
prop54_yes_per double precision,
prop54_no_per double precision,
prop55_yes_per double precision,
prop55_no_per double precision,
prop56_yes_per double precision,
prop56_no_per double precision,
prop57_yes_per double precision,
prop57_no_per double precision,
prop58_yes_per double precision,
prop58_no_per double precision,
prop59_yes_per double precision,
prop59_no_per double precision,
prop60_yes_per double precision,
prop60_no_per double precision,
prop61_yes_per double precision,
prop61_no_per double precision,
prop62_yes_per double precision,
prop62_no_per double precision,
prop63_yes_per double precision,
prop63_no_per double precision,
prop64_yes_per double precision,
prop64_no_per double precision,
prop65_yes_per double precision,
prop65_no_per double precision,
prop66_yes_per double precision,
prop66_no_per double precision,
prop67_yes_per double precision,
prop67_no_per double precision,
PRIMARY KEY( pct16 )
);
